#include <stdio.h>
#include <windows.h>
#include <conio.h>

int GameTitle() {
	system("cls");
	printf("\n\n\n\n\n\n\n\n\n");
	printf("\t\t   '||' '||''''|  '||''|.   '||'  |'      .|'''.|   ..|''||   '||'  '|' '||'       .|'''.|  \n");
	printf("\t\t    ||   ||  .     ||   ||   || .'        ||..  '  .|'    ||   ||    |   ||        ||..  '  \n");
	printf("\t\t    ||   ||''|     ||''|'    ||'|.         ''|||.  ||      ||  ||    |   ||         ''|||.  \n");
	printf("\t\t    ||   ||        ||   |.   ||  ||      .     '|| '|.     ||  ||    |   ||       .     '|| \n");
	printf("\t\t|| .|'  .||.....| .||.  '|' .||.  ||.    |'....|'   ''|...|'    '|..'   .||.....| |'....|'  \n");
	printf("\t\t '''  \n");
	printf("\n\t\t\t      ｗｉｔｈ ＡＲＴＯＲＩＡＳ ＯＦ ＴＨＥ ＡＢＩＳＳ ＥＤＩＴＩＯＮ \n\n\n");
	printf("\n\n\n\n\t\t\t\t　　　ＰＲＥＳＳ　ＡＮＹ　ＫＥＹ　ＴＯ　ＳＴＡＲＴ");
	_getch();
	system("cls");
	printf("\n\n\n\n\n\n\n");
	printf("\n\t\t\t\t*―――――――――――――――――――――――――――――――――*\n");
	printf("\n\n\n\t\t\t\t	最大化表示での　プレイを推奨します\n\t\t\t\t	変更し終わったら　エンターキーを　押してください\n\n");
	printf("\n\n\t\t\t\t*―――――――――――――――――――――――――――――――――*");
	getchar();
	system("cls");

	printf(" ┌――――┬――――┬――――┬――――┐\n");
	printf(" │ゆうしゃ│せんし　│そうりょ│けんじゃ│\n");
	printf(" ├――――┼――――┼――――┼――――┤\n");
	printf(" │HP   45 │HP    0 │HP    0 │HP    0 │\n");
	printf(" │MP   28 │MP    0 │MP   11 │MP    2 │\n");
	printf(" └――――┴――――┴――――┴――――┘\n");
	printf("\n	　　　　＿＿＿\n");
	printf("	　　　／＼⊥／＼\n");
	printf("	　　 /＼／＿＼／ヽ\n");
	printf("	　|ヽL_/ (◎) ﾍ＿|ﾉ|\n");
	printf("	　ヽ＿卯ヘ工ヘ卯＿ノ\n");
	printf("	　　|-|((･><･))|-|\n");
	printf("	＜￣ヽヽ)vｪｪv(ノノ￣＞\n");
	printf("	（＼＿ﾆ人ﾋｪｪﾀ人ﾆ＿／)\n");
	printf("	　＼～∩((＿))8/～／\n");
	printf("	　 |＼||／)￣8/)／|\n");
	printf("	　 ⊂ニ ／_(二 ニ⊃\n");
	printf("	　 ﾊ (／(▼▼)＼) |\n");
	printf("	　/ / |-|>―<|-|ヽヽ\n");
	printf("	`/ /　|-|￣￣|-| ヽヽ\n");
	printf("	/ /　 |-ヽ＿ノ-|　| |\n");
	printf("	Ｖ　| ヽ⊥⊥⊥ノ| | |\n");
	printf("	/　 ヾ　　　　 ノ | |\n");
	printf("	＼＿＿ ヾ　　ノ ＿|ノ\n");
	printf("	　／⌒＞―――＜⌒＼\n");
	printf("	　￣￣　　　　　￣￣\n");
	printf("\n\nせんしは　いきたえた！\n");
	getchar();
	printf("そうりょは　いきたえた！\n");
	getchar();
	printf("けんじゃは　いきたえた！\n");
	getchar();
	system("cls");

	printf(" ┌――――┬――――┬――――┬――――┐\n");
	printf(" │ゆうしゃ│せんし　│そうりょ│けんじゃ│\n");
	printf(" ├――――┼――――┼――――┼――――┤\n");
	printf(" │HP   45 │HP    0 │HP    0 │HP    0 │\n");
	printf(" │MP   28 │MP    0 │MP   11 │MP    2 │\n");
	printf(" └――――┴――――┴――――┴――――┘\n");

	printf("\n	　　　　＿＿＿\n");
	printf("	　　　／＼⊥／＼\n");
	printf("	　　 /＼／＿＼／ヽ\n");
	printf("	　|ヽL_/ (◎) ﾍ＿|ﾉ|\n");
	printf("	　ヽ＿卯ヘ工ヘ卯＿ノ\n");
	printf("	　　|-|((･><･))|-|\n");
	printf("	＜￣ヽヽ)vｪｪv(ノノ￣＞\n");
	printf("	（＼＿ﾆ人ﾋｪｪﾀ人ﾆ＿／)\n");
	printf("	　＼～∩((＿))8/～／\n");
	printf("	　 |＼||／)￣8/)／|\n");
	printf("	　 ⊂ニ ／_(二 ニ⊃\n");
	printf("	　 ﾊ (／(▼▼)＼) |\n");
	printf("	　/ / |-|>―<|-|ヽヽ\n");
	printf("	`/ /　|-|￣￣|-| ヽヽ\n");
	printf("	/ /　 |-ヽ＿ノ-|　| |\n");
	printf("	Ｖ　| ヽ⊥⊥⊥ノ| | |\n");
	printf("	/　 ヾ　　　　 ノ | |\n");
	printf("	＼＿＿ ヾ　　ノ ＿|ノ\n");
	printf("	　／⌒＞―――＜⌒＼\n");
	printf("	　￣￣　　　　　￣￣\n");
	printf("\n\nゆうしゃの　こうげき！");
	getchar();
	printf("\nゾーマに　128の　ダメージを　あたえた！");
	getchar();
	system("cls");

	printf(" ┌――――┬――――┬――――┬――――┐\n");
	printf(" │ゆうしゃ│せんし　│そうりょ│けんじゃ│\n");
	printf(" ├――――┼――――┼――――┼――――┤\n");
	printf(" │HP   45 │HP    0 │HP    0 │HP    0 │\n");
	printf(" │MP   28 │MP    0 │MP   11 │MP    2 │\n");
	printf(" └――――┴――――┴――――┴――――┘\n");
	printf("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nゆうしゃたちは　ゾーマを　やっつけた！");
	getchar();
	printf("\nせかいに　へいわが　おとずれた！");
	getchar();
	system("cls");
	printf("\n\n\n\n\n\n\t\tゆうしゃ:　せかいを『すくえ』ても　みんなを『すくえ』なかった！\n");
	getchar();
	printf("\t\t\t　 ちからだ…　ちからがほしい！！\n");
	getchar();
	printf("\t\t\t　 だれもをすくい　だれもをたおせる　あっとうてきな　ちからが！！\n");
	getchar();
	printf("\n\n\t\t\t　 ゆうしゃの　さけびは　むなしくひびいた…\n");
	getchar();
	printf("\n\n\n\t\t？？？:　　ククク…　ちからがほしいか？\n");
	getchar();
	printf("\n\t\t　　　 　　ならば『たたかえ』！　きょうてきと　たたかい　けいけんをつむのだ！\n");
	getchar();
	printf("\n\t\t　　　 　　あいては　わたしが　よういしてやろう…　いきのこったとき　おまえは　あっとうてきな　ちからを　てにしているだろう…\n");
	getchar();
	printf("\n\t\t　　　 　　『おう』を　なのれる　あっとうてきな　ちからだ！！\n");
	getchar();
	system("cls");
	printf("\n\n\n\n\n\n\t\tあたりは　やみに　つつまれた！　くらやみから　『じゃあく』な　たましい　を　かんじる…\n");
	getchar();
	printf("\n\t\tくらやみから　なにものかが　おそいかかってくる！\n");
	getchar();
	printf("\n\n\n\t\tゆうしゃ:　いきのこってやる！　すべてを『すくう』ちからを　てにいれる…！\n");
	getchar();
	printf("\n\t\tゆうしゃは　けんをとり　たたかいに　そなえた…！\n");
	getchar();
	system("cls");
	printf("\n\n\t\t＃ せんとうコマンドせつめい ＃\n\n");
	printf("\n\n\t\tたたかう\t:\tあなたの　もっている　つるぎで　てきに　きりかかる\n\t\t\t\t\tダメージルーレットのあたいが　『95』　いじょうのとき だいダメージをあたえる\n\n");
	printf("\n\t\tじゅもん\t:\tこうげき　かいふく　ほじょ　ぶつりわざ　しゅるいは　さまざま\n");
	printf("\t\t\t\t\tつかうには　MP（マジックポイント）が　ひつよう\n\n");
	printf("\n\t\tちょうはつ\t:\tきめぜりふを　はなち　てきの　こころを　ゆさぶる\n");
	printf("\t\t\t\t\tせいこうすれば　あいてを　じゃくたいか　させる\n\n");
	printf("\n\t\tパリィ\t\t:\tせいしんを　しゅうちゅうし　てきの　ぶつりこうげきを　みきる\n");
	printf("\t\t\t\t\tパリィルーレットのあたいが　『50』　いじょうのとき　せいこう\n");
	printf("\t\t\t\t\tせいこうすれば　あいてに　ふかいきずを　あたえるが\n");
	printf("\t\t\t\t\tしっぱいすれば　じぶんが　ふかいきずを　おう\n\n");
	printf("\n\t\tぼうぎょ\t:\tてきの　こうげきを　ぼうぎょたいせいで　うけとめる\n");
	printf("\t\t\t\t\tあいての　ぶつりこうげきダメージを　けいげんできる\n\n");
	printf("\n\t\tにげる\t\t:\tかなわないと　かんじたら　にげるのも　さくのうち\n");
	printf("\t\t\t\t\tエスケープルーレットのあたいが　『34』　いじょうのとき　せいこう\n\n");
	printf("\n\n\n\t\tエンターキーを　おすと　キャラクタークリエイト画面に　移動します");
	getchar();
	return 0;
}